package dev.dmayr.chatapplication.domain.model

data class ChatMessage(
    val id: Long = 0, // Unique ID for local persistence, auto-generated by Room
    val senderId: String,
    val receiverId: String, // Or chatRoomId for group chats
    val content: String,
    val timestamp: Long,
    val isRead: Boolean = false // Local status for message read/unread
)
